### PR TITLE
add photos to README and quelpa instructions

### PR DESCRIPTION
**Pull request by chookity-pokk**
I fixed the seemingly broken screenshots(?) by just adding my own. I think I got what you were going for? 

I also added instructions for Quelpa installation.

### CODE REVIEW

**Comment by karthink** [comment]
Thank you. I will look at this after I'm back at my pc, but in the meantime
could you check the image-test branch and let me know if the images show
up? I tried to fix the images there.

**Comment by chookity-pokk** [comment]
Ah, I didn't see that branch. The images do seem to show up there!

**Comment by karthink** [comment]
Very well. In that case can we add your screenshots to a showcase section
in the readme? I haven't seen them yet, but I'm guessing your emacs looks
different so it'll be good to have some variety. I'll merge the image-test
branch into master soon.

**Comment by karthink** [comment]
@chookity-pokk I've merged the image-test branch. Could you add your screenshots to a "Showcase" or "Screenshots" section in the README?

**Pull request closed without merging**
